/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ex.personal.pruebabiometrico;

import com.sun.jna.ptr.IntByReference;
import ex.personal.pruebabiometrico.fs88lib.FTRAnsiSDK;
import ex.personal.pruebabiometrico.fs88lib.FTRScanAPI;
import ex.personal.pruebabiometrico.gui.IconoHuella;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.awt.image.DataBuffer;
import java.io.File;
import javax.swing.ImageIcon;

/**
 *
 * @author Francis
 */
public class FrmHuella extends javax.swing.JFrame {

    private IconoHuella iconoHuella;
    private final FTRAnsiSDK ftrAnsiSDK = FTRAnsiSDK.INSTANCE;
    private final FTRScanAPI ftrScanAPI = FTRScanAPI.INSTANCE;
    public boolean activo = false;

    public enum TipoOperacion {
        CAPTURAR, ENROLAR, IDENTIFICAR, VERIFICAR
    }

    private class HiloOperacion implements Runnable {

        private TipoOperacion operacion;

        public HiloOperacion(TipoOperacion operacion) {
            this.operacion = operacion;
        }
        
        @Override
        public void run() {
            while (activo) {
                switch (operacion) {
                    case CAPTURAR:
                        obtenerCaptura();
                }
            }
        }

        private void obtenerCaptura() {
            IntByReference equipo = ftrScanAPI.ftrScanOpenDevice();
            FTRScanAPI.FTRSCAN_IMAGE_SIZE.ByReference imageSize = new FTRScanAPI.FTRSCAN_IMAGE_SIZE.ByReference();
            ftrScanAPI.ftrScanGetImageSize(equipo, imageSize);
            byte[] imagen = new byte[imageSize.nImageSize];
            boolean captura = ftrAnsiSDK.ftrAnsiSdkCaptureImage(equipo, imagen);
            if (captura) {
                iconoHuella.setImage(byteToImagen(imageSize.nWidth, imageSize.nHeight, imagen));
                lblHuella.repaint();
            } 
        }

    }

    public Image byteToImagen(int ancho, int alto, byte[] pBitmap) {
        BufferedImage hImage = new BufferedImage(ancho,
                alto,
                BufferedImage.TYPE_BYTE_GRAY);
        DataBuffer db1 = hImage.getRaster().getDataBuffer();
        for (int i = 0; i < db1.getSize(); i++) {
            db1.setElem(i, pBitmap[i]);
        }
        return hImage;
    }

    /**
     * Creates new form FrmHuella
     */
    public FrmHuella() {
        initComponents();
        iconoHuella = new IconoHuella(this.lblHuella.getPreferredSize().width, this.lblHuella.getPreferredSize().height);
        iconoHuella.setImage(createImageIcon("Futronic.JPG").getImage());
        this.lblHuella.setIcon(iconoHuella);
    }

    private ImageIcon createImageIcon(String path) {
        File fichero = new File(path);
        if (fichero.exists()) {
            return new ImageIcon(fichero.getAbsolutePath());
        } else {
            System.err.println("Couldn't find file: " + path);
            return null;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipal = new javax.swing.JPanel();
        pnlDatos = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        lblHuella = new javax.swing.JLabel();
        pnlHuella = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlPrincipal.setLayout(new java.awt.BorderLayout());

        pnlDatos.setLayout(new java.awt.GridBagLayout());

        jButton1.setText("Capturar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        pnlDatos.add(jButton1, new java.awt.GridBagConstraints());

        jButton2.setText("Detener");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        pnlDatos.add(jButton2, new java.awt.GridBagConstraints());

        lblHuella.setMaximumSize(new java.awt.Dimension(200, 200));
        lblHuella.setMinimumSize(new java.awt.Dimension(200, 200));
        lblHuella.setPreferredSize(new java.awt.Dimension(200, 200));
        pnlDatos.add(lblHuella, new java.awt.GridBagConstraints());

        pnlPrincipal.add(pnlDatos, java.awt.BorderLayout.CENTER);

        pnlHuella.setLayout(new java.awt.GridBagLayout());
        pnlPrincipal.add(pnlHuella, java.awt.BorderLayout.EAST);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.activo = false;
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.activo = true;
        Thread realizarTarea = new Thread(new HiloOperacion(TipoOperacion.CAPTURAR));
        realizarTarea.start();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmHuella.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmHuella.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmHuella.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmHuella.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmHuella().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel lblHuella;
    private javax.swing.JPanel pnlDatos;
    private javax.swing.JPanel pnlHuella;
    private javax.swing.JPanel pnlPrincipal;
    // End of variables declaration//GEN-END:variables
}
